spring:
  security:
    user:
      name: pragra
      password: pragra
  datasource:
    url: jdbc:h2:file:./app.db
    username: sa
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
